before_install:
 - travis_retry sudo add-apt-repository -y ppa:hets/hets
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get build-dep hets
script:
 - make
 - ./hets -V
 - export HETS_MAGIC=$PWD/magic/hets.magic
 - make check

